### ISSUE TITLE
关于 rigger-ng 支持 ctags 的安装与配置

### ISSUE THREAD

**Issue by leiming** [xcodecraft/rigger-ng#10]
因为 rigger-ng 不是标准的 pylon 项目，因此无法使用`<F11>` 即 pylon_ide 插件的索引功能。

为方便 rigger 项目的开发，可使用 [python-ctags](https://code.google.com/p/python-ctags/) ，方法为：
## 1. 安装python-ctags

（开发机23 已经装好）

``` python
sudo easy_install python-ctags
```
## 2. 建立索引

在项目根目录下运行命令 ：

``` bash
ctags -R --tag-relative --fields=+afmikKlnsStz --languages=+python -f `pwd`/tags
```
- 再次进入项目后，即可使用`Ctrl + ]` 使用 ctags 了:

![image](https://cloud.githubusercontent.com/assets/2059859/6632065/423b85e6-c96b-11e4-9801-841f45a0b1f4.png)

**Comment by zwj** [comment]
Reading http://code.google.com/p/python-ctags/ 

code.google.com  被墙了！

**Comment by leiming** [comment]
@zwj 在内网 `~/.bash_profile` 中写入如下代理应该就可以了：

```bash
export http_proxy='http://10.16.13.18:8080'
export HTTPS_PROXY='http://10.16.13.18:8080'
```

**Comment by yangwm** [comment]
赞！
